apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-1
  namespace: argocd
spec:
  project: rocketman
  source:
    repoURL: https://github.com/zenardi-org/react-app-1.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rocketman
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true